/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'major' : IDL.Text,
  'name' : IDL.Text,
  'available' : IDL.Bool,
  'portfolioUrl' : IDL.Opt(IDL.Text),
  'skills' : IDL.Vec(IDL.Text),
});
export const Time = IDL.Int;
export const Project = IDL.Record({
  'id' : IDL.Nat,
  'figmaUrl' : IDL.Opt(IDL.Text),
  'title' : IDL.Text,
  'skillsOffered' : IDL.Vec(IDL.Text),
  'owner' : IDL.Principal,
  'description' : IDL.Text,
  'githubUrl' : IDL.Opt(IDL.Text),
  'timestamp' : Time,
  'skillsNeeded' : IDL.Vec(IDL.Text),
});
export const ConversationPreview = IDL.Record({
  'lastMessage' : IDL.Text,
  'otherParty' : IDL.Principal,
  'unreadCount' : IDL.Nat,
  'timestamp' : Time,
});
export const Message = IDL.Record({
  'to' : IDL.Principal,
  'body' : IDL.Text,
  'from' : IDL.Principal,
  'read' : IDL.Bool,
  'projectId' : IDL.Opt(IDL.Nat),
  'timestamp' : Time,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createProject' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Vec(IDL.Text),
        IDL.Vec(IDL.Text),
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
      ],
      [IDL.Nat],
      [],
    ),
  'getAllProfiles' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
  'getAllProjects' : IDL.Func([], [IDL.Vec(Project)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getConversationPreview' : IDL.Func(
      [],
      [IDL.Vec(ConversationPreview)],
      ['query'],
    ),
  'getMessageThread' : IDL.Func([IDL.Principal], [IDL.Vec(Message)], ['query']),
  'getProject' : IDL.Func([IDL.Nat], [IDL.Opt(Project)], ['query']),
  'getProjectsBySkill' : IDL.Func([IDL.Text], [IDL.Vec(Project)], ['query']),
  'getUnreadMessageCount' : IDL.Func([], [IDL.Nat], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'markThreadRead' : IDL.Func([IDL.Principal], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'sendMessage' : IDL.Func([IDL.Principal, IDL.Text, IDL.Opt(IDL.Nat)], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({
    'major' : IDL.Text,
    'name' : IDL.Text,
    'available' : IDL.Bool,
    'portfolioUrl' : IDL.Opt(IDL.Text),
    'skills' : IDL.Vec(IDL.Text),
  });
  const Time = IDL.Int;
  const Project = IDL.Record({
    'id' : IDL.Nat,
    'figmaUrl' : IDL.Opt(IDL.Text),
    'title' : IDL.Text,
    'skillsOffered' : IDL.Vec(IDL.Text),
    'owner' : IDL.Principal,
    'description' : IDL.Text,
    'githubUrl' : IDL.Opt(IDL.Text),
    'timestamp' : Time,
    'skillsNeeded' : IDL.Vec(IDL.Text),
  });
  const ConversationPreview = IDL.Record({
    'lastMessage' : IDL.Text,
    'otherParty' : IDL.Principal,
    'unreadCount' : IDL.Nat,
    'timestamp' : Time,
  });
  const Message = IDL.Record({
    'to' : IDL.Principal,
    'body' : IDL.Text,
    'from' : IDL.Principal,
    'read' : IDL.Bool,
    'projectId' : IDL.Opt(IDL.Nat),
    'timestamp' : Time,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createProject' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Vec(IDL.Text),
          IDL.Vec(IDL.Text),
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
        ],
        [IDL.Nat],
        [],
      ),
    'getAllProfiles' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
    'getAllProjects' : IDL.Func([], [IDL.Vec(Project)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getConversationPreview' : IDL.Func(
        [],
        [IDL.Vec(ConversationPreview)],
        ['query'],
      ),
    'getMessageThread' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(Message)],
        ['query'],
      ),
    'getProject' : IDL.Func([IDL.Nat], [IDL.Opt(Project)], ['query']),
    'getProjectsBySkill' : IDL.Func([IDL.Text], [IDL.Vec(Project)], ['query']),
    'getUnreadMessageCount' : IDL.Func([], [IDL.Nat], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'markThreadRead' : IDL.Func([IDL.Principal], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'sendMessage' : IDL.Func(
        [IDL.Principal, IDL.Text, IDL.Opt(IDL.Nat)],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };