/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ConversationPreview {
  'lastMessage' : string,
  'otherParty' : Principal,
  'unreadCount' : bigint,
  'timestamp' : Time,
}
export interface Message {
  'to' : Principal,
  'body' : string,
  'from' : Principal,
  'read' : boolean,
  'projectId' : [] | [bigint],
  'timestamp' : Time,
}
export interface Project {
  'id' : bigint,
  'figmaUrl' : [] | [string],
  'title' : string,
  'skillsOffered' : Array<string>,
  'owner' : Principal,
  'description' : string,
  'githubUrl' : [] | [string],
  'timestamp' : Time,
  'skillsNeeded' : Array<string>,
}
export type Time = bigint;
export interface UserProfile {
  'major' : string,
  'name' : string,
  'available' : boolean,
  'portfolioUrl' : [] | [string],
  'skills' : Array<string>,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createProject' : ActorMethod<
    [
      string,
      string,
      Array<string>,
      Array<string>,
      [] | [string],
      [] | [string],
    ],
    bigint
  >,
  'getAllProfiles' : ActorMethod<[], Array<UserProfile>>,
  'getAllProjects' : ActorMethod<[], Array<Project>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getConversationPreview' : ActorMethod<[], Array<ConversationPreview>>,
  'getMessageThread' : ActorMethod<[Principal], Array<Message>>,
  'getProject' : ActorMethod<[bigint], [] | [Project]>,
  'getProjectsBySkill' : ActorMethod<[string], Array<Project>>,
  'getUnreadMessageCount' : ActorMethod<[], bigint>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'markThreadRead' : ActorMethod<[Principal], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'sendMessage' : ActorMethod<[Principal, string, [] | [bigint]], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];